services:
  db:
    image: postgres:18
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST:-db}
      - POSTGRES_USER=${POSTGRES_USER:-dipdup}
      - POSTGRES_DB=${POSTGRES_DB:-noble}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-dipdup} -d ${POSTGRES_DB:-noble}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    logging: &indexer-logging
      options:
        max-size: 10m
        max-file: "5"

  indexer:
    image: ghcr.io/noble-indexer/indexer:${TAG:-master}
    build:
      dockerfile: build/indexer/Dockerfile
      context: .
    env_file:
      - .env
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db
    logging: *indexer-logging

  api:
    image: ghcr.io/noble-indexer/api:${TAG:-master}
    build:
      dockerfile: build/api/Dockerfile
      context: .
    env_file:
      - .env
    restart: always
    ports:
      - ${API_PORT:-9876}:9876
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db
    logging: *indexer-logging

volumes:
  db:
