name: Build
permissions:
  contents: read
  pull-requests: read
  packages: write

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'master'

jobs:
  build_indexer:
    name: Build Indexer
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: ghcr.io
      DOCKER_IMAGE_BASE: ${{ github.repository }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Indexer image tags & labels
        id: meta-indexer
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_BASE }}/indexer

      - name: Indexer image build & push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: build/indexer/Dockerfile
          push: true
          cache-from: type=gha,scope=indexer
          cache-to: type=gha,mode=max,scope=indexer
          tags: ${{ steps.meta-indexer.outputs.tags }}
          labels: ${{ steps.meta-indexer.outputs.labels }}

  build_api:
    name: Build API
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: ghcr.io
      DOCKER_IMAGE_BASE: ${{ github.repository }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: API image tags & labels
        id: meta-api
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_BASE }}/api

      - name: API image build & push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: build/api/Dockerfile
          push: true
          cache-from: type=gha,scope=api
          cache-to: type=gha,mode=max,scope=api
          tags: ${{ steps.meta-api.outputs.tags }}
          labels: ${{ steps.meta-api.outputs.labels }}

  build_contract_metadata:
    name: Build Contract Metadata Resolver
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: ghcr.io
      DOCKER_IMAGE_BASE: ${{ github.repository }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Contract metadata image tags & labels
        id: meta-contract-metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_BASE }}/contract-metadata

      - name: Contract metadata image build & push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: build/contract_metadata_resolver/Dockerfile
          push: true
          cache-from: type=gha,scope=contract-metadata
          cache-to: type=gha,mode=max,scope=contract-metadata
          tags: ${{ steps.meta-contract-metadata.outputs.tags }}
          labels: ${{ steps.meta-contract-metadata.outputs.labels }}

  build_contract_verifier:
    name: Build Contract Verifier
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: ghcr.io
      DOCKER_IMAGE_BASE: ${{ github.repository }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Contract verifier image tags & labels
        id: meta-contract-verifier
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_BASE }}/contract-verifier

      - name: Contract verifier image build & push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: build/contract_verifier/Dockerfile
          push: true
          cache-from: type=gha,scope=contract-verifier
          cache-to: type=gha,mode=max,scope=contract-verifier
          tags: ${{ steps.meta-contract-verifier.outputs.tags }}
          labels: ${{ steps.meta-contract-verifier.outputs.labels }}

  build_token_metadata:
    name: Build Token Metadata Resolver
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: ghcr.io
      DOCKER_IMAGE_BASE: ${{ github.repository }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Token metadata image tags & labels
        id: meta-token-metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_BASE }}/token-metadata

      - name: Token metadata image build & push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: build/token_metadata_resolver/Dockerfile
          push: true
          cache-from: type=gha,scope=token-metadata
          cache-to: type=gha,mode=max,scope=token-metadata
          tags: ${{ steps.meta-token-metadata.outputs.tags }}
          labels: ${{ steps.meta-token-metadata.outputs.labels }}
